### PR TITLE
fix: add type declarations for css export (TypeScript 6 compat)

### LINKED ISSUE #16346: TypeScript 6 compatibility: import '@payloadcms/next/css' fails with TS2882
### Describe the Bug

TypeScript 6 enables [`noUncheckedSideEffectImports`](https://www.typescriptlang.org/tsconfig/noUncheckedSideEffectImports.html) by default ([announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-6-0/)). This causes all three `import
  '@payloadcms/next/css'` statements generated by `create-payload-app` to fail with **TS2882**.

`Type error: Cannot find module or type declarations for side-effect import of '@payloadcms/next/css'.`

### Link to the code that reproduces this issue

https://github.com/andershermansen/payload-repro-ts6-css-import

### Reproduction Steps

1. Create a new payload app from blank template 
2. Update to typescript 6.0.3
3. Build

Actual:
Build fails

Expected:
Build successful

### Which area(s) are affected?

area: core

### Environment Info

```text
Binaries:
  Node: 24.15.0
  npm: 11.12.1
  Yarn: N/A
  pnpm: 10.33.0
Relevant Packages:
  payload: 3.83.0
  next: 16.2.3
  @payloadcms/db-mongodb: 3.83.0
  @payloadcms/graphql: 3.83.0
  @payloadcms/next/utilities: 3.83.0
  @payloadcms/richtext-lexical: 3.83.0
  @payloadcms/translations: 3.83.0
  @payloadcms/ui/shared: 3.83.0
  react: 19.2.4
  react-dom: 19.2.4
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 25.4.0: Thu Mar 19 19:30:44 PDT 2026; root:xnu-12377.101.15~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
```

### PR DESCRIPTION
**Pull request by andershermansen**
### What?

Add TypeScript type declarations for the `./css` package export in `@payloadcms/next`.

### Why?

TypeScript 6 enables [`noUncheckedSideEffectImports`](https://www.typescriptlang.org/tsconfig/noUncheckedSideEffectImports.html) by default. This causes `import '@payloadcms/next/css'` — present in all three files generated by `create-payload-app` — to fail with:

error TS2882: Cannot find module or type declarations for side-effect import of '@payloadcms/next/css'.

The published `./css` export currently has no `types` field:

  ```json
  "./css": {
    "import": "./dist/prod/styles.css",
    "default": "./dist/prod/styles.css"
  }
```

### How?

Add src/exports/css.ts as a regular TypeScript source file (consistent with all other exports so the existing build pipeline produces dist/exports/css.d.ts. Then wire the types field into both dev and publishConfig exports.

**Testing:**
Tested locally by copying the new files
`cp ../../payload/packages/next/dist/exports/css.* node_modules/@payloadcms/next/dist/exports`
and pacthing the package.json manually:
```
--- original-package.json       2026-04-22 10:43:26
+++ package.json        2026-04-22 10:43:57
@@ -24,6 +24,7 @@
   "exports": {
     "./css": {
       "import": "./dist/prod/styles.css",
+      "types": "./dist/exports/css.d.ts",
       "default": "./dist/prod/styles.css"
     },
     "./withPayload": {
```
after that my test project builds fine with typescript 6.0.3

Fixes #16346

### CODE REVIEW

**Comment by andershermansen** [comment]
After the build of the reproduction repo with manual patching the production run `pnpm start` also works fine in my testing. That is it shows the correct layout.

**Review by denolfe — APPROVED** [review]
Thanks @andershermansen !
