### ISSUE TITLE
doc.setPassword is not a function when trying to change password from admin panel

### ISSUE THREAD

**Issue by alamit** [payloadcms/payload#1572]
# Bug Report

## Steps to Reproduce

1. Launch payload
2. Create a user
3. Try to change password in the admin panel.

## Other Details

Payload: v1.2.2
Chrome: Version 107.0.5304.121 (Official Build) (x86_64)

**Comment by alamit** [comment]
Working on my side with 1.2.3.
Thank you very much for your reactivity!
