### ISSUE TITLE
Multi-locale `tenantSelectorLabel` stopped working in 3.38.0

### ISSUE THREAD

**Issue by BohdanK-W32** [payloadcms/payload#12443]
### Describe the Bug

Before 3.38.0 I used `tenantSelectorLabel` with i18n support and everything was working with no issues.
After upgrade to 3.38.0 this approach stopped working due to multi-tenant plugin treats this option only as a string.
Which leads to `label.toLowerCase is not a function` runtime error in `src/components/TenantSelector/index.tsx` (of multi-tenant plugin) when using 18n label approach

![Image](https://github.com/user-attachments/assets/d22a270f-3fca-4e9b-b9f9-48b860ea81d0)

P.S.: Also you need to update Functionallity Bug issue template, in the "Which area(s) are affected?" question there is no option for "plugin: multi-tenant"

### Link to the code that reproduces this issue

no link.

### Reproduction Steps

1. Setup multi-tenant plugin with `tenantSelectorLabel` as object with locales, example: `{ en: 'Tenant', uk: 'Тенант' }`
2. Check for runtime error
3. Switch `tenantSelectorLabel` to string, example: `'Tenant'`
4. Everything works fine now, but without i18n support

### Which area(s) are affected? (Select all that apply)

plugin: other, area: ui

### Environment Info

```text
Payload: 3.38.0
```
