### PR TITLE
fix(db-postgres): migration template type error

### LINKED ISSUE #7402: Migrations no longer work correctly
### Link to reproduction

_No response_

### Payload Version

3.0.0-beta.70

### Node Version

22.5.1

### Next.js Version

15.0.0-rc.0

### Describe the Bug

Changes introduced in PR #7320 changed the migration function structure, making it unable to compile. 

If left unchanged, you get the following:

```
Type error: Property 'execute' does not exist on type 'LibSQLDatabase<Record<string, never>> | PostgresDB'.
  Property 'execute' does not exist on type 'LibSQLDatabase<Record<string, never>>'.
  2 |
  3 | export async function up({ payload, req }: MigrateUpArgs): Promise<void> {
> 4 | await payload.db.drizzle.execute(sql`
```

I've attempted to create a new migration, to see what changed, however it still leads to a broken file, shown below:

```
Type error: Property 'db' does not exist on type 'MigrateUpArgs'.
  2 | 
  3 | export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
> 4 | await db.execute(sql`
```

### Reproduction Steps

* Attempt to run any migration from before 3.0.0-beta.68 inclusive.
* Attempt to create a new migration through `payload migrate:create example`.

### Adapters and Plugins

db-postgres

### PR DESCRIPTION
**Pull request by DanRibbens**
## Description

Fixes #7402

This fixes a regression from changes to the postgres migration template that were incorrect. It also fixes other type errors for `payload.db.drizzle` which needed to be declared for postgres to avoid confusing it with Libsql for SQLite.

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by DanRibbens** [comment]
This has been released in 3.0.0-canary.6d066c2
