### ISSUE TITLE
Migrations no longer work correctly

### ISSUE THREAD

**Issue by dinckelman** [payloadcms/payload#7402]
### Payload Version

3.0.0-beta.70

### Node Version

22.5.1

### Next.js Version

15.0.0-rc.0

### Describe the Bug

Changes introduced in PR #7320 changed the migration function structure, making it unable to compile. 

If left unchanged, you get the following:

```
Type error: Property 'execute' does not exist on type 'LibSQLDatabase<Record<string, never>> | PostgresDB'.
  Property 'execute' does not exist on type 'LibSQLDatabase<Record<string, never>>'.
  2 |
  3 | export async function up({ payload, req }: MigrateUpArgs): Promise<void> {
> 4 | await payload.db.drizzle.execute(sql`
```

I've attempted to create a new migration, to see what changed, however it still leads to a broken file, shown below:

```
Type error: Property 'db' does not exist on type 'MigrateUpArgs'.
  2 | 
  3 | export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
> 4 | await db.execute(sql`
```

### Reproduction Steps

* Attempt to run any migration from before 3.0.0-beta.68 inclusive.
* Attempt to create a new migration through `payload migrate:create example`.

### Adapters and Plugins

db-postgres

**Comment by DanRibbens** [comment]
Hey @dinckelman, thank you for reporting this. I cannot believe we didn't catch this before releaes.

I've published `3.0.0-canary.6d066c2` that has the fix for you and anyone else that needs this immediately. @HarleySalas
You will have to install all the @payloadcms modules with the exact same version:
```
"payload": "3.0.0-canary.6d066c2",
"@payloadcms/db-postgres": "3.0.0-canary.6d066c2",
....etc
```

Cheers!
